=== gibtmirdas/Master1-MPO7/n-genes_0.9/config/genetic.dtd
<!--
    This dtd declares a config file for a genetic algorithm.

    Fontignie Jacques

    It is important to note that each element can use a reference for object. The most of the time, this is totally
    useless.
-->


<!ELEMENT program (constant*,temporary?,genetic)>

<!ENTITY % schema  SYSTEM "schema/config.dtd">

%schema;

<!-- Definiion of the temporary elements, can be used to create some objects thta will be referenced -->
<!ELEMENT temporary (object*)>

<!ELEMENT constant EMPTY>
<!ATTLIST constant
    NAME CDATA #REQUIRED
    VALUE CDATA #REQUIRED
>

<!-- Definition of the main genetic programming function -->
<!ELEMENT genetic (population,context,individual,(mutation|crossover|operator|pipe|breeder)+,selection,(event|log)*,halt+)>
<!ATTLIST genetic
            NAME CDATA #IMPLIED
            CLASS CDATA "ch.unige.ng.bin.Genetic"
            popSize CDATA #REQUIRED
            time (true|false) "true"
            safeShutting (true|false) "false"
            id ID #IMPLIED
            reference IDREF #IMPLIED
>

<!ELEMENT population (object*,parameter*)>
<!ATTLIST population
            CLASS CDATA "ch.unige.ng.populations.BasicPopulation"
            NAME CDATA #IMPLIED
            id ID #IMPLIED
            reference IDREF #IMPLIED
>

<!-- It is necessary to determine the type of the individual -->
<!ELEMENT individual (initializer?, parameter*,((geneFactory,fitness)|(fitness,geneFactory)),printer?,object*)>
<!ATTLIST individual
            CLASS CDATA "ch.unige.ng.species.stackGP.StackGPIndividual"
            indSize CDATA #IMPLIED
            id ID #IMPLIED
            reference IDREF #IMPLIED
>

<!ELEMENT initializer (parameter|object)*>
<!ATTLIST initializer
        CLASS CDATA #IMPLIED
        id ID #IMPLIED
        reference IDREF #IMPLIED
>

<!-- The context contains essentially the number generator and the problem itself-->
<!ELEMENT context (random,(object|parameter))>
<!ATTLIST context
                CLASS CDATA "ch.unige.ng.gen.Context"
                id ID #IMPLIED
                reference IDREF #IMPLIED
>

<!-- the random generator -->
<!ELEMENT random (object|parameter)*>
<!ATTLIST random
                CLASS CDATA #REQUIRED
                seed CDATA #IMPLIED
>

<!-- the fitness function -->
<!ELEMENT fitness (parameter| object)*>
<!ATTLIST fitness
            NAME CDATA #IMPLIED
            CLASS CDATA #IMPLIED
            id ID #IMPLIED
            reference IDREF #IMPLIED
>

<!-- The printer used to print the individual -->
<!ELEMENT printer (parameter|object)*>
<!ATTLIST printer
            NAME CDATA #IMPLIED
            CLASS CDATA #REQUIRED
            id ID #IMPLIED
>

<!-- It defines how does the function work -->
<!ELEMENT geneFactory (parameter|object)*>
<!ATTLIST geneFactory
            NAME CDATA #IMPLIED
            CLASS CDATA #REQUIRED
            id ID #IMPLIED
>

<!-- It defines the different operator -->
<!ELEMENT operator (object|parameter)*>
<!ATTLIST operator
            NAME CDATA #IMPLIED
            CLASS CDATA #REQUIRED
            id ID #IMPLIED
>

<!-- It defines the breeder-->
<!ELEMENT breeder (mutation|crossover|operator|pipe|breeder|object|parameter)+ >
<!ATTLIST breeder
            CLASS CDATA "ch.unige.ng.ops.utils.Breeder"
            id ID #IMPLIED
            reference IDREF #IMPLIED
            probabilities CDATA #REQUIRED
>


<!-- It defines the mutation algorithm -->
<!ELEMENT mutation (object|parameter)*>
<!ATTLIST mutation
            NAME CDATA #IMPLIED
            CLASS CDATA #IMPLIED
            id ID #IMPLIED
            reference IDREF #IMPLIED
>

<!ELEMENT pipe (((object|parameter)*,(mutation*|crossover*|operator*|breeder*)+)*)>
<!ATTLIST pipe
            NAME CDATA #IMPLIED
            CLASS CDATA "ch.unige.ng.ops.utils.Pipe"
            probability CDATA #IMPLIED
            id ID #IMPLIED
>

<!-- It defines the crossover that can be made on an individual -->
<!ELEMENT crossover (object|parameter)*>
<!ATTLIST crossover
            NAME CDATA #IMPLIED
            CLASS CDATA #IMPLIED
            id ID #IMPLIED
            reference IDREF #IMPLIED
>


<!-- the selection mode -->
<!ELEMENT selection (parameter|object)*>
<!ATTLIST selection
            NAME CDATA #IMPLIED
            CLASS CDATA #IMPLIED
            id ID #IMPLIED
            reference IDREF #IMPLIED
>

<!ELEMENT event (endCondition?,frequencyCondition*,condition*,listener)>
<!ATTLIST event
            CLASS CDATA "ch.unige.ng.timer.EventTimer"
            id ID #IMPLIED
>


<!ELEMENT log ((endCondition|frequencyCondition|condition)+,logger,(object|parameter)*)>
<!ATTLIST log
            CLASS CDATA "ch.unige.ng.timer.GeneticTimer"
            id ID #IMPLIED
 >

<!ELEMENT endCondition EMPTY>
<!ATTLIST endCondition
            CLASS CDATA "ch.unige.ng.timer.conditions.EndCondition"
            id ID #IMPLIED
>

<!ELEMENT frequencyCondition EMPTY>
<!ATTLIST frequencyCondition
            CLASS CDATA "ch.unige.ng.timer.conditions.FrequencyCondition"
            frequency CDATA #REQUIRED
            id ID #IMPLIED
>


<!ELEMENT condition (parameter|object)*>
<!ATTLIST condition
            CLASS CDATA #REQUIRED
            id ID #IMPLIED
>


<!ELEMENT logger (statistic+,writer+,parameter*,object*) >
<!ATTLIST logger
            CLASS CDATA "ch.unige.ng.tools.io.Logger"
            id ID #IMPLIED
>

<!ELEMENT listener (parameter|object)* >
<!ATTLIST listener
            CLASS CDATA #IMPLIED
            reference IDREF #IMPLIED
            id ID #IMPLIED
>


<!ELEMENT statistic (parameter|object)*>

<!ATTLIST statistic
            NAME CDATA #IMPLIED
            CLASS CDATA #IMPLIED
            reference IDREF #IMPLIED
            id ID #IMPLIED
>

<!ELEMENT writer (object*,parameter*,fileprinter*)>
<!ATTLIST writer
            CLASS CDATA #REQUIRED
            console (true|false) #IMPLIED
            id ID #IMPLIED
>

<!ELEMENT fileprinter (parameter|object)*>
<!ATTLIST fileprinter
            CLASS CDATA "ch.unige.ng.tools.io.FilePrinter"
            NAME CDATA #IMPLIED
            clobber (true|false) "false"
            compressed (true|false) "false"
            id ID #IMPLIED
>

<!ELEMENT halt (parameter|object)*>
<!ATTLIST halt
            CLASS CDATA #REQUIRED
            id ID #IMPLIED
>

<!ELEMENT object (parameter|object)*>
<!ATTLIST object
            NAME CDATA #IMPLIED
            CLASS CDATA #IMPLIED
            id ID #IMPLIED
            reference IDREF #IMPLIED
>

<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
            NAME CDATA #REQUIRED
            VALUE CDATA #REQUIRED
>

=== gibtmirdas/Master1-MPO7/n-genes_0.9/config/sphereGP.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE program SYSTEM "./genetic.dtd">

<!-- A config file to resolve the minimum of the michalewicz function:



 -->

<program>

    <constant NAME="min" VALUE="-600"/>
    <constant NAME="max" VALUE="600"/>
    <constant NAME="maxSize" VALUE="1000"/>

    <!-- Creating the genetic algorithm -->
    <genetic popSize="100" safeShutting="true">
        <population/>

        <!-- Declaring the context -->
        <context CLASS="ch.unige.ng.gen.Context" id="context">
            <random CLASS="ch.unige.ng.tools.rng.MersenneTwister" seed="#seed#"/>
        </context>

        <!-- Declaring the individual with the fitness and the factory -->
        <individual CLASS="ch.unige.ng.species.VariableSizeIndividual" indSize="#maxSize#">
            <initializer CLASS="ch.unige.ng.species.initializers.stackGP.FullInitializer">
                <parameter NAME="minDepth" VALUE="5"/>
                <parameter NAME="maxDepth" VALUE="5"/>
                <object reference="context"/>
            </initializer>

            <fitness CLASS="ch.unige.ng.fitness.FormulaFitness" id="fitness">
                <parameter NAME="min" VALUE="#min#"/>
                <parameter NAME="max" VALUE="#max#"/>
                <parameter NAME="numTests" VALUE="60"/>
                <parameter NAME="equation" VALUE="x*x + y*y"/>
                <object reference="context"/>
                <object CLASS="ch.unige.ng.species.stackGP.evaluations.Evaluator" id="evaluator">
                    <parameter NAME="iterationMax" VALUE="10000"/>
                </object>
            </fitness>

            <geneFactory CLASS="ch.unige.ng.species.stackGP.factories.ProbabilityStackGPGeneFactory">
                <parameter NAME="terminalProbability" VALUE="0.1"/>
                <object reference="fitness"/>
                <object reference="context"/>
                <!-- Defining operation list -->
                <object CLASS="ch.unige.ng.species.stackGP.operations.doubles.Add"/>
                <object CLASS="ch.unige.ng.species.stackGP.operations.doubles.Subst"/>
                <object CLASS="ch.unige.ng.species.stackGP.operations.doubles.Mul"/>
                <object CLASS="ch.unige.ng.species.stackGP.operations.doubles.Div"/>
            </geneFactory>            


        </individual>

        <pipe>
            <crossover CLASS="ch.unige.ng.ops.crossover.stackGP.SubTreeCrossover">
                <parameter NAME="cleaning" VALUE="true"/>
            </crossover>
            <mutation CLASS="ch.unige.ng.ops.mutation.stackGP.SmartPromoter">
                <parameter NAME="maxSize" VALUE="10"/>
            </mutation>
        </pipe>

        <!-- Defining the selection method-->
        <selection CLASS="ch.unige.ng.ops.select.KTournamentSelector" id="selector">
            <parameter NAME="size" VALUE="5"/>
        </selection>

        <!-- Running a timer -->

        <event>
            <condition CLASS="ch.unige.ng.timer.conditions.EndCondition"/>
            <listener CLASS="ch.unige.ng.timer.PopulationModifier">
                <object CLASS="ch.unige.ng.ops.mutation.stackGP.BackwardCleaner"/>
            </listener>
        </event>

        <log>
            <frequencyCondition frequency="1"/>


            <logger>
                <statistic CLASS="ch.unige.ng.statistics.BestStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.MedianStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.WorstStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.EverBestStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.MeanLengthStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.WallClockStatistic"/>

                <writer CLASS="ch.unige.ng.tools.io.writer.DefaultWriter" console="true">
                    <parameter NAME="header" VALUE="true"/>
                    <parameter NAME="separator" VALUE="\t"/>
                </writer>
            </logger>
        </log>

        <log>
            <endCondition/>
            <logger>
                <statistic CLASS="ch.unige.ng.statistics.BestPrinter"/>
                <writer CLASS="ch.unige.ng.tools.io.writer.DefaultWriter" console="true"/>
            </logger>
        </log>


        <halt CLASS="ch.unige.ng.halt.MaximumFitnessHalting">
            <parameter NAME="threshold" VALUE="EPS"/>
        </halt>
        <halt CLASS="ch.unige.ng.halt.MaximumStepHalting">
            <parameter NAME="step" VALUE="1000"/>
        </halt>


    </genetic>
</program>

=== gibtmirdas/Master1-MPO7/n-genes_0.9/config/santafe.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE program SYSTEM "./genetic.dtd">

<program>
    <constant NAME="maxSize" VALUE="100"/>
    <constant NAME="size" VALUE="20"/>
    <constant NAME="numIndividuals" VALUE="1024"/>
    <constant NAME="mode" VALUE="normal"/>
    <genetic popSize="#numIndividuals#" time="true">

        <population/>


        <context id="context">
            <random CLASS="ch.unige.ng.tools.rng.MersenneTwister" seed="#seed#"/>

        </context>

        <individual CLASS="ch.unige.ng.species.VariableSizeIndividual" indSize="#maxSize#">

            <initializer CLASS="ch.unige.ng.species.initializers.BasicInitializer">
                <parameter NAME="size" VALUE="#size#"/>
            </initializer>

            <!-- Declaring fitness -->
            <fitness CLASS="ch.unige.ng.problems.santafe.fitness.SantaFeFitness" id="fitness">
                <object CLASS="ch.unige.ng.problems.santafe.evaluations.ControlEvaluator" id="evaluator">
                    <parameter NAME="iterationMax" VALUE="400"/>
                </object>
                <object CLASS="ch.unige.ng.problems.santafe.context.FileBoard" id="board">
                    <parameter NAME="filename" VALUE="config/santafe/santafe.trl"/>
                </object>
            </fitness>

            <geneFactory CLASS="ch.unige.ng.species.stackGP.factories.ProbabilityStackGPGeneFactory">
                <parameter NAME="terminalProbability" VALUE="0.05"/>
                <object reference="fitness"/>
                <object reference="context"/>
                <!-- Defining operation list -->
                <object CLASS="ch.unige.ng.problems.santafe.operations.Move">
                    <object reference="board"/>
                </object>
                <object CLASS="ch.unige.ng.problems.santafe.operations.Left"/>
                <object CLASS="ch.unige.ng.problems.santafe.operations.Right"/>
                <object CLASS="ch.unige.ng.problems.santafe.operations.IfFoodAhead">
                    <object reference="board"/>
                </object>
                <object CLASS="ch.unige.ng.species.stackGP.operations.controls.Else"/>
                <object CLASS="ch.unige.ng.species.stackGP.operations.controls.End"/>
                <!--                <object CLASS="ch.unige.ng.problems.santafe.operations.Prog"/>-->
            </geneFactory>

        </individual>


        <breeder probabilities="0.3;0.7">
            <object CLASS="ch.unige.ng.ops.mutation.GeneralMutation">
                <parameter NAME="mutationProbability" VALUE="0.8"/>
                <parameter NAME="insertionProbability" VALUE="0.1"/>
                <parameter NAME="deletionProbability" VALUE="0.1"/>
            </object>

            <object CLASS="ch.unige.ng.ops.crossover.VarSizeOnePointCrossOver">
                <parameter NAME="politic" VALUE="RANDOM"/>
            </object>
        </breeder>


        <selection CLASS="ch.unige.ng.ops.select.KTournamentSelector">
            <parameter NAME="size" VALUE="7"/>
        </selection>

        <log>
            <endCondition/>
            <frequencyCondition frequency="1"/>
            <logger>
                <statistic CLASS="ch.unige.ng.statistics.BestStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.MeanStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.WorstStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.EverBestStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.STDStatistic"/>

                <writer CLASS="ch.unige.ng.tools.io.writer.DefaultWriter" console="true">
                    <parameter NAME="separator" VALUE="\t"/>
                </writer>
            </logger>
        </log>
        <log>
            <endCondition/>
            <frequencyCondition frequency="10"/>
            <logger>
                <statistic CLASS="ch.unige.ng.statistics.BestPrinter"/>
                <writer CLASS="ch.unige.ng.tools.io.writer.DefaultWriter" console="true">
                    <parameter NAME="separator" VALUE="\t"/>
                </writer>
            </logger>
        </log>


        <log>
            <endCondition/>
            <frequencyCondition frequency="5"/>
            <logger>
                <statistic CLASS="ch.unige.ng.statistics.BestPrinter"/>
                <writer CLASS="ch.unige.ng.problems.santafe.io.BoardPainter">
                    <object reference="evaluator" NAME="evaluator"/>
                    <object reference="board" NAME="board"/>
                </writer>
            </logger>
        </log>


        <halt CLASS="ch.unige.ng.halt.MaximumStepHalting">
            <parameter NAME="step" VALUE="1000"/>
        </halt>

    </genetic>
</program>

=== gibtmirdas/Master1-MPO7/n-genes_0.9/config/tsp.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE program SYSTEM "./genetic.dtd">

<program>
    <constant NAME="seed" VALUE="0"/>
    <genetic popSize="1000">
        <population/>

        <context id="context">
            <random CLASS="ch.unige.ng.tools.rng.MersenneTwister" seed="#seed#"/>
        </context>

        <individual CLASS="ch.unige.ng.species.PermutableIndividual" id="prototype">

            <geneFactory CLASS="ch.unige.ng.problems.tsp.TSPGeneFactory">
                <parameter NAME="fileName" VALUE="config/tsp/problem1.tsp"/>
                <object reference="context"/>
            </geneFactory>

            <fitness CLASS="ch.unige.ng.problems.tsp.TSPFitness"/>

        </individual>


        <crossover CLASS="ch.unige.ng.ops.permutables.SwapCrossover"/>                   

        <mutation CLASS="ch.unige.ng.ops.permutables.SwapMutation"/>

        <selection CLASS="ch.unige.ng.ops.select.KTournamentSelector">
            <parameter NAME="size" VALUE="5"/>
        </selection>

        <!-- Running a timer -->
        <log>
            <!-- The timer will be fired at frequency 2-->
            <frequencyCondition frequency="5"/>
            <!--            <endCondition/>-->

            <!-- The logger that output data -->
            <logger>
                <!-- we will print the best individual -->
                <statistic CLASS="ch.unige.ng.statistics.BestStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.MeanStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.WorstStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.EverBestStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.STDStatistic"/>
                <writer CLASS="ch.unige.ng.tools.io.writer.DefaultWriter" console="true">
                    <parameter NAME="header" VALUE="true"/>
                    <parameter NAME="separator" VALUE="\t"/>
                </writer>
            </logger>
        </log>


        <!-- Creating halting functions -->

        <!-- If the threshold is under EPS, the program is terminated -->
        <halt CLASS="ch.unige.ng.halt.MaximumStepHalting">
            <parameter NAME="step" VALUE="5000"/>
        </halt>

    </genetic>
</program>

=== gibtmirdas/Master1-MPO7/n-genes_0.9/config/griewangk.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE program SYSTEM "./genetic.dtd">

<program>
    <constant NAME="maxSize" VALUE="10000"/>
    <constant NAME="numIndividuals" VALUE="100"/>
    <constant NAME="mode" VALUE="normal"/>
    <genetic popSize="#numIndividuals#" time="true">
        <!--        <population CLASS="populations.CachingPopulation">-->
        <!--            <parameter NAME="cacheSize" VALUE="100M"/>-->
        <!--        </population>-->
        <population/>

        <!-- Declaring the context -->
        <context id="context">
            <random CLASS="ch.unige.ng.tools.rng.MersenneTwister" seed="12"/>
        </context>

        <individual CLASS="ch.unige.ng.species.VariableSizeIndividual" indSize="#maxSize#">

            <initializer CLASS="ch.unige.ng.species.initializers.stackGP.FullInitializer">
                <parameter NAME="minDepth" VALUE="4"/>
                <parameter NAME="maxDepth" VALUE="6"/>
                <object reference="context"/>
            </initializer>

            <!-- Declaring fitness -->
            <fitness CLASS="ch.unige.ng.fitness.FormulaFitness" id="fitness">
                <parameter NAME="min" VALUE="-100"/>
                <parameter NAME="max" VALUE="100"/>
                <parameter NAME="numTests" VALUE="20"/>
                <parameter NAME="equation" VALUE="x*x +  40"/>
                <object reference="context"/>
                <object CLASS="ch.unige.ng.species.stackGP.evaluations.Evaluator" id="evaluator">
                    <parameter NAME="iterationMax" VALUE="10000"/>
                </object>
            </fitness>

            <geneFactory CLASS="ch.unige.ng.species.stackGP.factories.ProbabilityStackGPGeneFactory">
                <parameter NAME="terminalProbability" VALUE="0.1"/>
                <object reference="fitness"/>
                <object reference="context"/>
                <!-- Defining operation list -->
                <object CLASS="ch.unige.ng.species.stackGP.operations.doubles.Add"/>
                <object CLASS="ch.unige.ng.species.stackGP.operations.doubles.Subst"/>
                <object CLASS="ch.unige.ng.species.stackGP.operations.doubles.Mul"/>
                <object CLASS="ch.unige.ng.species.stackGP.operations.doubles.Div"/>
                <!--                <object CLASS="ch.unige.ng.species.stackGP.operations.doubles.Sin"/>-->
                <!--                <object CLASS="ch.unige.ng.species.stackGP.operations.doubles.Cos"/>-->
                <!--                <object CLASS="ch.unige.ng.species.stackGP.operations.doubles.Exp"/>-->
                <!--                <object CLASS="ch.unige.ng.species.stackGP.operations.doubles.Log"/>-->
            </geneFactory>


        </individual>

        <pipe>

            <crossover CLASS="ch.unige.ng.ops.crossover.stackGP.SubTreeCrossover"/>

            <breeder probabilities="0.5 ; 0.5">

                <mutation CLASS="ch.unige.ng.ops.utils.Replicator"/>
                <mutation CLASS="ch.unige.ng.ops.mutation.stackGP.SmartPromoter">
                    <parameter NAME="maxSize" VALUE="10"/>
                </mutation>

            </breeder>

        </pipe>

        <selection CLASS="ch.unige.ng.ops.select.KTournamentSelector">
            <parameter NAME="size" VALUE="7"/>
        </selection>


        <log>
            <endCondition/>
            <frequencyCondition frequency="1"/>
            <logger>
                <statistic CLASS="ch.unige.ng.statistics.BestStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.MeanStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.WorstStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.EverBestStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.STDStatistic"/>

                <writer CLASS="ch.unige.ng.tools.io.writer.DefaultWriter" console="true">
                    <parameter NAME="separator" VALUE="\t"/>
                    <fileprinter clobber="true" NAME="filePrinter">
                        <parameter NAME="filename" VALUE="test.txt"/>
                    </fileprinter>
                </writer>
            </logger>
        </log>

        <halt CLASS="ch.unige.ng.halt.MaximumStepHalting">
            <parameter NAME="step" VALUE="10000"/>
        </halt>

    </genetic>
</program>

=== gibtmirdas/Master1-MPO7/src/tp7/tp7.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE program SYSTEM "../../n-genes_0.9/config/genetic.dtd">
<program>

	<constant NAME="min" VALUE="-600"/>
	<constant NAME="max" VALUE="600"/>
	<constant NAME="maxSize" VALUE="30"/>
	<constant NAME="maxStep" VALUE="100"/>
	<constant NAME="popSize" VALUE="200"/>

	<!-- Creating the genetic algorithm -->
	<genetic popSize="#popSize#" safeShutting="true">
		<population/>

		<!-- Declaring the context -->
		<context CLASS="ch.unige.ng.gen.Context" id="context">
			<random CLASS="ch.unige.ng.tools.rng.JavaUtilRandom"/>
		</context>

		<!-- Declaring the individual with the fitness and the factory -->
		<individual CLASS="ch.unige.ng.species.VariableSizeIndividual" indSize="#maxSize#">
			<initializer CLASS="ch.unige.ng.species.initializers.stackGP.FullInitializer">
				<parameter NAME="minDepth" VALUE="3"/>
				<parameter NAME="maxDepth" VALUE="5"/>
				<object reference="context"/>
			</initializer>

			<fitness CLASS="tp7.CustomFitness" id="fitness">
				<parameter NAME="file" VALUE="src\lookup\learn_table.txt"/>
				<object CLASS="ch.unige.ng.species.stackGP.evaluations.Evaluator" id="evaluator">
					<parameter NAME="iterationMax" VALUE="1"/>
				</object>
			</fitness>

			<geneFactory CLASS="ch.unige.ng.species.stackGP.factories.SimpleStackGPGeneFactory">
				<object reference="context"/>
				<object reference="fitness"/>
				<!-- Defining operation list -->
				<object CLASS="ch.unige.ng.species.stackGP.operations.booleans.And"/>
				<object CLASS="ch.unige.ng.species.stackGP.operations.booleans.Not"/>
				<object CLASS="ch.unige.ng.species.stackGP.operations.booleans.Or"/>
				<object CLASS="ch.unige.ng.species.stackGP.operations.booleans.Xor"/>
			</geneFactory>

		</individual>

		<!--<pipe>-->
			<!--<crossover CLASS="ch.unige.ng.ops.crossover.stackGP.SubTreeCrossover">-->
				<!--<parameter NAME="cleaning" VALUE="true"/>-->
			<!--</crossover>-->
			<!--<mutation CLASS="ch.unige.ng.ops.mutation.stackGP.SmartPromoter">-->
				<!--<parameter NAME="maxSize" VALUE="2"/>-->
			<!--</mutation>-->
		<!--</pipe>-->
		<breeder probabilities="0.3;0.7">
			<object CLASS="ch.unige.ng.ops.mutation.GeneralMutation">
				<parameter NAME="mutationProbability" VALUE="0.3"/>
				<parameter NAME="insertionProbability" VALUE="0.4"/>
				<parameter NAME="deletionProbability" VALUE="0.3"/>
			</object>
			<object CLASS="ch.unige.ng.ops.crossover.VarSizeOnePointCrossOver">
				<parameter NAME="politic" VALUE="RANDOM"/>
			</object>
		</breeder>


		<!-- Defining the selection method-->
		<selection CLASS="ch.unige.ng.ops.select.KTournamentSelector" id="selector">
			<parameter NAME="size" VALUE="5"/>
		</selection>

		<!-- Running a timer -->
		<event>
			<condition CLASS="ch.unige.ng.timer.conditions.EndCondition" />
			<condition CLASS="ch.unige.ng.timer.conditions.FrequencyCondition">
				<parameter NAME="frequency" VALUE="1" />
			</condition>
			<listener CLASS="ch.unige.ng.timer.PopulationModifier">
				<object CLASS="ch.unige.ng.ops.mutation.stackGP.ForwardCleaner">
					<parameter NAME="deletionMode" VALUE="FITNESS_DESTRUCTIVE"/>
				</object>
			</listener>
		</event>

		<log>
			<frequencyCondition frequency="10"/>
			<logger>
				<statistic CLASS="ch.unige.ng.statistics.BestStatistic"/>
				<statistic CLASS="ch.unige.ng.statistics.MedianStatistic"/>
				<statistic CLASS="ch.unige.ng.statistics.WorstStatistic"/>
				<statistic CLASS="ch.unige.ng.statistics.EverBestStatistic"/>
				<statistic CLASS="ch.unige.ng.statistics.MeanLengthStatistic"/>
				<statistic CLASS="ch.unige.ng.statistics.WallClockStatistic"/>

				<writer CLASS="ch.unige.ng.tools.io.writer.DefaultWriter" console="true">
					<parameter NAME="header" VALUE="true"/>
					<parameter NAME="separator" VALUE="\t"/>
				</writer>
			</logger>
		</log>

		<log>
			<endCondition/>
			<logger>
				<statistic CLASS="ch.unige.ng.statistics.BestPrinter"/>
				<writer CLASS="ch.unige.ng.tools.io.writer.DefaultWriter" console="true"/>
			</logger>
		</log>

		<halt CLASS="ch.unige.ng.halt.MaximumFitnessHalting">
			<parameter NAME="threshold" VALUE="EPS"/>
		</halt>
		<halt CLASS="ch.unige.ng.halt.MaximumStepHalting">
			<parameter NAME="step" VALUE="#maxStep#"/>
		</halt>

	</genetic>
</program>

=== gibtmirdas/Master1-MPO7/tests/maxones.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE program SYSTEM "..\n-genes_0.9\config\genetic.dtd">
 
<program>
	<genetic popSize="100">
		<population/>
		<context id="context">
			<random CLASS="ch.unige.n-genes.tools.rng.MersenneTwister" seed="0"/>
		</context>
		<individual CLASS="ch.unige.n-genes.species.VectorIndividual" indSize="1000">
			<geneFactory CLASS="ch.unige.n-genes.species.booleans.BooleanGeneFactory">
				<object reference="context"/>
			</geneFactory>
			<fitness CLASS="tutorial.MaxOnesFitness"/>
		</individual>
		<pipe> 
			<mutation CLASS="ch.unige.n-genes.ops.mutation.BasicPointMutation" />
			<crossover CLASS="ch.unige.n-genes.ops.crossover.BasicOnePointCrossOver">
				<parameter NAME="politic" VALUE="RANDOM"/>
			</crossover>
		</pipe>
		<selection CLASS="ch.unige.n-genes.ops.select.KTournamentSelector"><!-- Put in pipe !? -->
			<parameter NAME="size" VALUE="5"/>
		</selection>
		<log>
			<frequencyCondition frequency="2"/>
			<endCondition/>
			<logger>
				<statistic CLASS="ch.unige.n-genes.statistics.BestStatistic"/>
				<statistic CLASS="ch.unige.n-genes.statistics.MeanStatistic"/>
				<statistic CLASS="ch.unige.n-genes.statistics.WorstStatistic"/>
				<writer CLASS="ch.unige.n-genes.tools.io.writer.DefaultWriter" console="true">
					<parameter NAME="separator" VALUE="\t"/>
				</writer>
			</logger>
		</log>
	</genetic>
</program>
