=== gibtmirdas/Master1-MPO7/n-genes_0.9/config/genetic.dtd
<!--
    This dtd declares a config file for a genetic algorithm.

    Fontignie Jacques

    It is important to note that each element can use a reference for object. The most of the time, this is totally
    useless.
-->


<!ELEMENT program (constant*,temporary?,genetic)>

<!ENTITY % schema  SYSTEM "schema/config.dtd">

%schema;

<!-- Definiion of the temporary elements, can be used to create some objects thta will be referenced -->
<!ELEMENT temporary (object*)>

<!ELEMENT constant EMPTY>
<!ATTLIST constant
    NAME CDATA #REQUIRED
    VALUE CDATA #REQUIRED
>

<!-- Definition of the main genetic programming function -->
<!ELEMENT genetic (population,context,individual,(mutation|crossover|operator|pipe|breeder)+,selection,(event|log)*,halt+)>
<!ATTLIST genetic
            NAME CDATA #IMPLIED
            CLASS CDATA "ch.unige.ng.bin.Genetic"
            popSize CDATA #REQUIRED
            time (true|false) "true"
            safeShutting (true|false) "false"
            id ID #IMPLIED
            reference IDREF #IMPLIED
>

<!ELEMENT population (object*,parameter*)>
<!ATTLIST population
            CLASS CDATA "ch.unige.ng.populations.BasicPopulation"
            NAME CDATA #IMPLIED
            id ID #IMPLIED
            reference IDREF #IMPLIED
>

<!-- It is necessary to determine the type of the individual -->
<!ELEMENT individual (initializer?, parameter*,((geneFactory,fitness)|(fitness,geneFactory)),printer?,object*)>
<!ATTLIST individual
            CLASS CDATA "ch.unige.ng.species.stackGP.StackGPIndividual"
            indSize CDATA #IMPLIED
            id ID #IMPLIED
            reference IDREF #IMPLIED
>

<!ELEMENT initializer (parameter|object)*>
<!ATTLIST initializer
        CLASS CDATA #IMPLIED
        id ID #IMPLIED
        reference IDREF #IMPLIED
>

<!-- The context contains essentially the number generator and the problem itself-->
<!ELEMENT context (random,(object|parameter))>
<!ATTLIST context
                CLASS CDATA "ch.unige.ng.gen.Context"
                id ID #IMPLIED
                reference IDREF #IMPLIED
>

<!-- the random generator -->
<!ELEMENT random (object|parameter)*>
<!ATTLIST random
                CLASS CDATA #REQUIRED
                seed CDATA #IMPLIED
>

<!-- the fitness function -->
<!ELEMENT fitness (parameter| object)*>
<!ATTLIST fitness
            NAME CDATA #IMPLIED
            CLASS CDATA #IMPLIED
            id ID #IMPLIED
            reference IDREF #IMPLIED
>

<!-- The printer used to print the individual -->
<!ELEMENT printer (parameter|object)*>
<!ATTLIST printer
            NAME CDATA #IMPLIED
            CLASS CDATA #REQUIRED
            id ID #IMPLIED
>

<!-- It defines how does the function work -->
<!ELEMENT geneFactory (parameter|object)*>
<!ATTLIST geneFactory
            NAME CDATA #IMPLIED
            CLASS CDATA #REQUIRED
            id ID #IMPLIED
>

<!-- It defines the different operator -->
<!ELEMENT operator (object|parameter)*>
<!ATTLIST operator
            NAME CDATA #IMPLIED
            CLASS CDATA #REQUIRED
            id ID #IMPLIED
>

<!-- It defines the breeder-->
<!ELEMENT breeder (mutation|crossover|operator|pipe|breeder|object|parameter)+ >
<!ATTLIST breeder
            CLASS CDATA "ch.unige.ng.ops.utils.Breeder"
            id ID #IMPLIED
            reference IDREF #IMPLIED
            probabilities CDATA #REQUIRED
>


<!-- It defines the mutation algorithm -->
<!ELEMENT mutation (object|parameter)*>
<!ATTLIST mutation
            NAME CDATA #IMPLIED
            CLASS CDATA #IMPLIED
            id ID #IMPLIED
            reference IDREF #IMPLIED
>

<!ELEMENT pipe (((object|parameter)*,(mutation*|crossover*|operator*|breeder*)+)*)>
<!ATTLIST pipe
            NAME CDATA #IMPLIED
            CLASS CDATA "ch.unige.ng.ops.utils.Pipe"
            probability CDATA #IMPLIED
            id ID #IMPLIED
>

<!-- It defines the crossover that can be made on an individual -->
<!ELEMENT crossover (object|parameter)*>
<!ATTLIST crossover
            NAME CDATA #IMPLIED
            CLASS CDATA #IMPLIED
            id ID #IMPLIED
            reference IDREF #IMPLIED
>


<!-- the selection mode -->
<!ELEMENT selection (parameter|object)*>
<!ATTLIST selection
            NAME CDATA #IMPLIED
            CLASS CDATA #IMPLIED
            id ID #IMPLIED
            reference IDREF #IMPLIED
>

<!ELEMENT event (endCondition?,frequencyCondition*,condition*,listener)>
<!ATTLIST event
            CLASS CDATA "ch.unige.ng.timer.EventTimer"
            id ID #IMPLIED
>


<!ELEMENT log ((endCondition|frequencyCondition|condition)+,logger,(object|parameter)*)>
<!ATTLIST log
            CLASS CDATA "ch.unige.ng.timer.GeneticTimer"
            id ID #IMPLIED
 >

<!ELEMENT endCondition EMPTY>
<!ATTLIST endCondition
            CLASS CDATA "ch.unige.ng.timer.conditions.EndCondition"
            id ID #IMPLIED
>

<!ELEMENT frequencyCondition EMPTY>
<!ATTLIST frequencyCondition
            CLASS CDATA "ch.unige.ng.timer.conditions.FrequencyCondition"
            frequency CDATA #REQUIRED
            id ID #IMPLIED
>


<!ELEMENT condition (parameter|object)*>
<!ATTLIST condition
            CLASS CDATA #REQUIRED
            id ID #IMPLIED
>


<!ELEMENT logger (statistic+,writer+,parameter*,object*) >
<!ATTLIST logger
            CLASS CDATA "ch.unige.ng.tools.io.Logger"
            id ID #IMPLIED
>

<!ELEMENT listener (parameter|object)* >
<!ATTLIST listener
            CLASS CDATA #IMPLIED
            reference IDREF #IMPLIED
            id ID #IMPLIED
>


<!ELEMENT statistic (parameter|object)*>

<!ATTLIST statistic
            NAME CDATA #IMPLIED
            CLASS CDATA #IMPLIED
            reference IDREF #IMPLIED
            id ID #IMPLIED
>

<!ELEMENT writer (object*,parameter*,fileprinter*)>
<!ATTLIST writer
            CLASS CDATA #REQUIRED
            console (true|false) #IMPLIED
            id ID #IMPLIED
>

<!ELEMENT fileprinter (parameter|object)*>
<!ATTLIST fileprinter
            CLASS CDATA "ch.unige.ng.tools.io.FilePrinter"
            NAME CDATA #IMPLIED
            clobber (true|false) "false"
            compressed (true|false) "false"
            id ID #IMPLIED
>

<!ELEMENT halt (parameter|object)*>
<!ATTLIST halt
            CLASS CDATA #REQUIRED
            id ID #IMPLIED
>

<!ELEMENT object (parameter|object)*>
<!ATTLIST object
            NAME CDATA #IMPLIED
            CLASS CDATA #IMPLIED
            id ID #IMPLIED
            reference IDREF #IMPLIED
>

<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
            NAME CDATA #REQUIRED
            VALUE CDATA #REQUIRED
>

=== gibtmirdas/Master1-MPO7/n-genes_0.9/config/nklandscape.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE program SYSTEM "./genetic.dtd">

<program>
    <constant NAME="seed" VALUE="0"/>
    <!-- Creating the genetic algorithm -->
    <genetic popSize="1000">
        <!--        <population CLASS="populations.CachingPopulation">-->
        <!--            <parameter NAME="cacheSize" VALUE="100M"/>-->
        <!--        </population>-->
        <population/>

        <!-- Declaring the context -->
        <context id="context">
            <random CLASS="ch.unige.ng.tools.rng.MersenneTwister" seed="#seed#"/>
            <!-- <random CLASS="ch.unige.ng.tools.rng.MersenneTwister" seed="0"/>-->
        </context>

        <!-- Declaring the individual with the fitness and the factory -->
        <individual CLASS="ch.unige.ng.species.VectorIndividual" indSize="1000" id="prototype">
            <!-- Creating the geneFactory: It is the object that decides hot to randomly create genes -->
            <geneFactory CLASS="ch.unige.ng.species.booleans.BooleanGeneFactory">
                <object reference="context"/>
            </geneFactory>

            <!-- Declaring the fitness used -->
            <fitness CLASS="ch.unige.ng.problems.nklandscape.NkLandscapeReader">
                <parameter NAME="filename" VALUE="config/nklandscape/nk1000_16.obj"/>
            </fitness>

        </individual>



        <!-- Determining the selection of a randomly gene -->

        <!-- Defining the mutation.
            The mutation is fired with a probability of 0.1 and one gene is modified
        -->
<!--        <pipe>-->
            <!-- The crossover is defined. The cutting point is decided randomly -->
            <crossover CLASS="ch.unige.ng.ops.crossover.BasicOnePointCrossOver">
                <parameter NAME="politic" VALUE="RANDOM"/>
            </crossover>

            <mutation CLASS="ch.unige.ng.ops.mutation.BasicPointMutation"/>
<!--        </pipe>-->

        <!-- Defining the selection method-->

        <selection CLASS="ch.unige.ng.ops.select.KTournamentSelector">
            <parameter NAME="size" VALUE="5"/>
        </selection>

        <!-- Running a timer -->
        <log>
            <!-- The timer will be fired at frequency 2-->
            <frequencyCondition frequency="5"/>
            <!--            <endCondition/>-->

            <!-- The logger that output data -->
            <logger>
                <!-- we will print the best individual -->
                <statistic CLASS="ch.unige.ng.statistics.BestStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.MeanStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.WorstStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.EverBestStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.STDStatistic"/>
                <statistic CLASS="ch.unige.ng.statistics.GenotypeStdStatistic"/>
                    <writer CLASS="ch.unige.ng.tools.io.writer.DefaultWriter" console="true">
                    <parameter NAME="header" VALUE="true"/>
                    <parameter NAME="separator" VALUE="\t"/>
                </writer>
            </logger>
        </log>


        <!-- Creating halting functions -->

        <!-- If the threshold is under EPS, the program is terminated -->
        <halt CLASS="ch.unige.ng.halt.MaximumStepHalting">
            <parameter NAME="step" VALUE="5000"/>
        </halt>

    </genetic>
</program>

=== gibtmirdas/Master1-MPO7/n-genes_0.9/tutorial/files/maxones.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<!-- This is the config file described in the tutorial 1 -->


<!-- change the following line to match your install
path -->
<!DOCTYPE program SYSTEM "../../tags/RECENT/config/genetic.dtd">

<program>

   <genetic popSize="100">
   
      <population/>

      <context id="context">
         <random CLASS="ch.unige.ng.tools.rng.MersenneTwister" seed="0"/>
      </context>



   <individual CLASS="ch.unige.ng.species.VectorIndividual" indSize="1000">

      <geneFactory CLASS="ch.unige.ng.species.booleans.BooleanGeneFactory">
         <object reference="context"/>
      </geneFactory>

     <fitness CLASS="tutorial.MaxOnesFitness"/>
    <!-- <fitness CLASS="ch.unige.ng.fitness.MaxOnes"/> -->

  </individual>

   <pipe>

      <mutation CLASS="ch.unige.ng.ops.mutation.BasicPointMutation" />

      <crossover CLASS="ch.unige.ng.ops.crossover.BasicOnePointCrossOver">
         <parameter NAME="politic" VALUE="RANDOM"/>
      </crossover>

   </pipe>

   <selection CLASS="ch.unige.ng.ops.select.KTournamentSelector">
      <parameter NAME="size" VALUE="5"/>
   </selection>

   <log>

      <frequencyCondition frequency="2"/>
      <endCondition/>

      <logger>

         <statistic CLASS="ch.unige.ng.statistics.BestStatistic"/>
         <statistic CLASS="ch.unige.ng.statistics.MeanStatistic"/>
         <statistic CLASS="ch.unige.ng.statistics.WorstStatistic"/>

         <writer CLASS="ch.unige.ng.tools.io.writer.DefaultWriter" console="true">
            <parameter NAME="separator" VALUE="\t"/>
         </writer>

       </logger>
    </log>

    <halt CLASS="ch.unige.ng.halt.MaximumFitnessHalting">
        <parameter NAME="threshold" VALUE="0"/>
    </halt>

   </genetic>

</program>
